# Permalinks
permalink:        pretty

# Setup
title:            Rohit Varkey Thankachan's blog!
tagline:          'rohitvarkey authors here'
description:      'I read about code. Write a little of it too! This blog lists my experiences while playing with code.'
url:              http://rohitvarkey.github.io
baseurl:          /
gems:             
                  -jemoji

author:
  name:           'Rohit Varkey Thankachan'
  url:            https://twitter.com/rohitvarkey

paginate:         5

# Custom vars
github:
  repo:           https://github.com/rohitvarkey
